import unittest
import functions


class TestApp(unittest.TestCase):

    def test_count(self):
        text = "CACATCGGGGACATCGGACATCGGGACACATCGGACATCGGTACATCGGCAACATCGGGGAACATCGGCGACATCGGAGCGATACATCGGACATCGGTAGACATCGGAACATCGGTACATCGGACATCGGATTGTACATCGGCACGACATCGGCCCTTCACATCGGAACATCGGTTGCACATCGGTGCCAATAAACATCGGACATCGGAGCACACATCGGTAGACATCGGAAGTGTACACATCGGTTACATCGGAACATCGGGCGTCACATCGGGAGGCACATCGGACAAACATCGGGCATACCATTCAGTTCACATCGGGGACATCGGATACATCGGGCCTACATCGGTCTGACATCGGCAGTGAGACATCGGTACATCGGGTACACATCGGCACATCGGGAACATCGGAGGCACATCGGCACATCGGACATCGGACATCGGAACATCGGACATCGGACATCGGGACATCGGACATCGGTAGTACATCGGACCGGTGATCTCGACATCGGACATCGGAACATCGGGCCCTAAACATCGGCACATCGGACATCGGCACATCGGATGATACATCGGTCACTGTACAGGAAACATCGGATTCCCACATCGGACATCGGGGACATCGGCACATCGGAGAAACATCGGTATACATCGGAGCCTTTCAGTACATCGGACATCGGACATCGGACATCGGTGTACATCGGATTCACATCGGACATCGGCAATGGACATCGGTCAGGTACATCGGCACATCGGACATCGGAACATCGGTTACATCGGCCGCAGGGACATCGGTCACATCGGCTAAAACATCGGTTCCATGTACATCGGACATCGGTTATTACATCGGACATCGGTGCATTCGGCTACTAACATCGGACATCGGGCCATCTGACATCGGTACATCGGACATCGGAACATCGGTACATCGGACATCGGCACATCGGCGAAAAACATCGGACATCGGAACATCGGGCCACTCACATCGG"
        pattern = "ACATCGGAC"
        count = functions.count(text, pattern)
        self.assertEqual(count, 26)

    def test_frequent_words(self):
        text = "ACGTTGCATGTCGCATGATGCATGAGAGCT"
        length = 4
        output = functions.get_frequent_pattern(text, length)
        self.assertEqual(output, "GCAT CATG")
